"""Collect retrievers/experiments/*/*/metrics.json into summary tables.

    python retrievers/aggregate.py

Writes experiments/summary.csv (one row per retriever x dataset x measure) and experiments/summary.md: one table
per benchmark with every dataset as a row, each retriever as a column, and the benchmark average at the bottom.
Averages are arithmetic means and follow each benchmark's convention:
  * BEIR:   the 12 CQADupStack forums are first averaged into one CQADupStack row (BEIR paper). The average is
            BEIR-13 (SPLADE++, ColBERTv2): every row except CQADupStack; MS MARCO and the licensed sets are not run.
  * CoIR:   the 6 CodeSearchNet and 6 CodeSearchNet-CCR languages are each averaged into one task (CoIR paper).
  * BRIGHT, MIRACL: plain mean over domains / languages.
  * MS MARCO: no average; dev, DL19 and DL20 are separate query sets over one corpus and are reported side by side.
An average is only reported when every dataset of the benchmark is present for that retriever.
"""
import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rbench import datasets  # noqa: E402
from rbench.common import EXP_DIR  # noqa: E402

RETRIEVER_ORDER = ['bm25', 'splade', 'e5', 'colbert']
COLLAPSE = {'beir/cqadupstack/': 'beir/cqadupstack', 'coir/codesearchnet/': 'coir/codesearchnet',
            'coir/codesearchnet-ccr/': 'coir/codesearchnet-ccr'}
NO_AVERAGE = {'msmarco'}
NOT_AVERAGED = {'beir': {'beir/cqadupstack'}}  # rows shown but left out of the average (BEIR-13)
AVERAGE_LABEL = {'beir': '**average (BEIR-13)**'}
TITLES = {'beir': 'BEIR', 'msmarco': 'MS MARCO (dev, TREC DL 2019/2020)', 'bright': 'BRIGHT', 'miracl': 'MIRACL (dev)',
          'coir': 'CoIR'}


def collapsed(name):
    for prefix, target in COLLAPSE.items():
        if name.startswith(prefix):
            return target
    return name


def load():
    rows = []
    for path in sorted(EXP_DIR.glob('*/*/metrics.json')):
        m = json.loads(path.read_text())
        for measure, value in m['metrics'].items():
            rows.append({'retriever': m['retriever'], 'model': m.get('model'), 'group': m['group'],
                         'dataset': m['dataset'], 'measure': measure, 'value': value})
    return pd.DataFrame(rows)


def group_table(df, group, measure):
    expected = [collapsed(n) for n in datasets.GROUPS[group]]
    expected = list(dict.fromkeys(expected))
    sub = df[(df['group'] == group) & (df['measure'] == measure)].copy()
    if sub.empty:
        return None
    sub['row'] = sub['dataset'].map(collapsed)
    n_parts = {r: sum(collapsed(n) == r for n in datasets.GROUPS[group]) for r in expected}
    # a collapsed row (e.g. CQADupStack) is only valid once all of its parts are in
    counts = sub.groupby(['retriever', 'row'])['value'].transform('count')
    sub = sub[counts == sub['row'].map(n_parts)]
    table = sub.groupby(['row', 'retriever'])['value'].mean().unstack('retriever')
    # the four main retrievers first, then --model variants (e.g. splade-splade-cocondenser-ensembledistil)
    columns = [r for r in RETRIEVER_ORDER if r in table.columns] + sorted(set(table.columns) - set(RETRIEVER_ORDER))
    table = table.reindex(index=[r for r in expected if r in table.index], columns=columns)
    if len(expected) > 1 and group not in NO_AVERAGE:
        averaged = [r for r in expected if r not in NOT_AVERAGED.get(group, ())]
        part = table.reindex(averaged)
        table.loc[AVERAGE_LABEL.get(group, '**average**')] = part.mean().where(part.notna().all())
    return table


def to_markdown(table):
    cols = list(table.columns)
    lines = ['| dataset | ' + ' | '.join(cols) + ' |', '|---|' + '---:|' * len(cols)]
    for row, vals in table.iterrows():
        cells = ['' if pd.isna(v) else f'{v:.4f}' for v in vals]
        best = max((v for v in vals if not pd.isna(v)), default=None)
        cells = [f'**{c}**' if best is not None and c and float(c) == round(best, 4) else c for c in cells]
        lines.append(f'| {row} | ' + ' | '.join(cells) + ' |')
    return '\n'.join(lines)


def main():
    df = load()
    if df.empty:
        raise SystemExit(f'no metrics.json under {EXP_DIR}')
    df.to_csv(EXP_DIR / 'summary.csv', index=False)
    parts = ['# Retriever benchmark summary', '',
             'Top-100 first-stage runs. Bold = best retriever on that row. Generated by `retrievers/aggregate.py`.', '']
    models = df.groupby('retriever')['model'].apply(lambda s: ', '.join(sorted(set(map(str, s))))).to_dict()
    parts += ['Models: ' + '; '.join(f'**{r}**: {m}' for r, m in models.items()), '']
    for group, title in TITLES.items():
        for measure in df.loc[df['group'] == group, 'measure'].unique():
            table = group_table(df, group, measure)
            if table is not None and not table.empty:
                parts += [f'## {title}: {measure}', '', to_markdown(table), '']
    (EXP_DIR / 'summary.md').write_text('\n'.join(parts))
    print('\n'.join(parts))
    print(f'wrote {EXP_DIR / "summary.md"} and {EXP_DIR / "summary.csv"}')


if __name__ == '__main__':
    main()
